version: '3.8'
services:
  dotnet:
  
  postgres-db:
    image: postgres
    container_name: postgres-container
    environment:
      POSTGRES_DB: polyana
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: changeme
    ports:
      - 5432:5432
